package model;
// Generated 19-dic-2023 22:25:50 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Citas generated by hbm2java
 */
public class Citas  implements java.io.Serializable {


     private Long id;
     private Long medicos;
     private Long pacientes;
     private Date fecha;
     private Enfermeros enfermeros;
     private Date createdAt;
     private Date updatedAt;
     private Set tratamientoses = new HashSet(0);

    public Citas() {
    }

	
    public Citas(Date fecha) {
        this.fecha = fecha;
    }
    
    public Citas (Long medicos, Long pacientes, Date fecha){
        this.medicos = medicos;
        this.pacientes = pacientes;
        this.fecha = fecha;
    }
    
    public Citas(Enfermeros enfermeros, long medicos, long pacientes, Date fecha, Date createdAt, Date updatedAt, Set tratamientoses) {
       this.enfermeros = enfermeros;
       this.medicos = medicos;
       this.pacientes = pacientes;
       this.fecha = fecha;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.tratamientoses = tratamientoses;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Enfermeros getEnfermeros() {
        return this.enfermeros;
    }
    
    public void setEnfermeros(Enfermeros enfermeros) {
        this.enfermeros = enfermeros;
    }
    public Long getMedicos() {
        return this.medicos;
    }
    
    public void setMedicos(Long medicos) {
        this.medicos = medicos;
    }
    public Long getPacientes() {
        return this.pacientes;
    }
    
    public void setPacientes(Long pacientes) {
        this.pacientes = pacientes;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
    public Set getTratamientoses() {
        return this.tratamientoses;
    }
    
    public void setTratamientoses(Set tratamientoses) {
        this.tratamientoses = tratamientoses;
    }




}


