package model;
// Generated 19-dic-2023 22:25:50 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Enfermeros generated by hbm2java
 */
public class Enfermeros  implements java.io.Serializable {


     private Long id;
     private Horarios horarios;
     private Users users;
     private String numeroColegiado;
     private String dni;
     private String nombre;
     private String apellido1;
     private String apellido2;
     private String telefono;
     private String sexo;
     private Date createdAt;
     private Date updatedAt;
     private Set citases = new HashSet(0);
     private Set pacienteses = new HashSet(0);

    public Enfermeros() {
    }

	
    public Enfermeros(String numeroColegiado, String dni, String nombre, String apellido1) {
        this.numeroColegiado = numeroColegiado;
        this.dni = dni;
        this.nombre = nombre;
        this.apellido1 = apellido1;
    }
    public Enfermeros(Horarios horarios, Users users, String numeroColegiado, String dni, String nombre, String apellido1, String apellido2, String telefono, String sexo, Date createdAt, Date updatedAt, Set citases, Set pacienteses) {
       this.horarios = horarios;
       this.users = users;
       this.numeroColegiado = numeroColegiado;
       this.dni = dni;
       this.nombre = nombre;
       this.apellido1 = apellido1;
       this.apellido2 = apellido2;
       this.telefono = telefono;
       this.sexo = sexo;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.citases = citases;
       this.pacienteses = pacienteses;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Horarios getHorarios() {
        return this.horarios;
    }
    
    public void setHorarios(Horarios horarios) {
        this.horarios = horarios;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public String getNumeroColegiado() {
        return this.numeroColegiado;
    }
    
    public void setNumeroColegiado(String numeroColegiado) {
        this.numeroColegiado = numeroColegiado;
    }
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido1() {
        return this.apellido1;
    }
    
    public void setApellido1(String apellido1) {
        this.apellido1 = apellido1;
    }
    public String getApellido2() {
        return this.apellido2;
    }
    
    public void setApellido2(String apellido2) {
        this.apellido2 = apellido2;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
    public Set getCitases() {
        return this.citases;
    }
    
    public void setCitases(Set citases) {
        this.citases = citases;
    }
    public Set getPacienteses() {
        return this.pacienteses;
    }
    
    public void setPacienteses(Set pacienteses) {
        this.pacienteses = pacienteses;
    }




}


