package model;
// Generated 19-dic-2023 22:25:50 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Horarios generated by hbm2java
 */
public class Horarios  implements java.io.Serializable {


     private Long id;
     private Date horaInicio;
     private Date horaFin;
     private short intervalo;
     private Date createdAt;
     private Date updatedAt;
     private Set enfermeroses = new HashSet(0);
     private Set medicoses = new HashSet(0);

    public Horarios() {
    }

	
    public Horarios(Date horaInicio, Date horaFin, short intervalo) {
        this.horaInicio = horaInicio;
        this.horaFin = horaFin;
        this.intervalo = intervalo;
    }
    public Horarios(Date horaInicio, Date horaFin, short intervalo, Date createdAt, Date updatedAt, Set enfermeroses, Set medicoses) {
       this.horaInicio = horaInicio;
       this.horaFin = horaFin;
       this.intervalo = intervalo;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.enfermeroses = enfermeroses;
       this.medicoses = medicoses;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Date getHoraInicio() {
        return this.horaInicio;
    }
    
    public void setHoraInicio(Date horaInicio) {
        this.horaInicio = horaInicio;
    }
    public Date getHoraFin() {
        return this.horaFin;
    }
    
    public void setHoraFin(Date horaFin) {
        this.horaFin = horaFin;
    }
    public short getIntervalo() {
        return this.intervalo;
    }
    
    public void setIntervalo(short intervalo) {
        this.intervalo = intervalo;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
    public Set getEnfermeroses() {
        return this.enfermeroses;
    }
    
    public void setEnfermeroses(Set enfermeroses) {
        this.enfermeroses = enfermeroses;
    }
    public Set getMedicoses() {
        return this.medicoses;
    }
    
    public void setMedicoses(Set medicoses) {
        this.medicoses = medicoses;
    }




}


