package model;
// Generated 19-dic-2023 22:25:50 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pacientes generated by hbm2java
 */
public class Pacientes  implements java.io.Serializable {


     private Long id;
     private Enfermeros enfermeros;
     private Medicos medicos;
     private Users users;
     private String sip;
     private String dni;
     private String nombre;
     private String apellido1;
     private String apellido2;
     private String telefono;
     private String sexo;
     private Date fechaNacimiento;
     private String localidad;
     private String calle;
     private String numero;
     private String puerta;
     private String piso;
     private Date createdAt;
     private Date updatedAt;
     private Set citases = new HashSet(0);

    public Pacientes() {
    }

	
    public Pacientes(String sip, String dni, String nombre, String apellido1) {
        this.sip = sip;
        this.dni = dni;
        this.nombre = nombre;
        this.apellido1 = apellido1;
    }
    
    public Pacientes(String sip, String dni, String nombre, String apellido1, String apellido2, String telefono, String localidad) {
        this.sip = sip;
        this.dni = dni;
        this.nombre = nombre;
        this.apellido1 = apellido1;
        this.apellido2 = apellido2;
        this.telefono = telefono;
        this.localidad = localidad;
    }
    
    public Pacientes(Enfermeros enfermeros, Medicos medicos, Users users, String sip, String dni, String nombre, String apellido1, String apellido2, String telefono, String sexo, Date fechaNacimiento, String localidad, String calle, String numero, String puerta, String piso, Date createdAt, Date updatedAt, Set citases) {
       this.enfermeros = enfermeros;
       this.medicos = medicos;
       this.users = users;
       this.sip = sip;
       this.dni = dni;
       this.nombre = nombre;
       this.apellido1 = apellido1;
       this.apellido2 = apellido2;
       this.telefono = telefono;
       this.sexo = sexo;
       this.fechaNacimiento = fechaNacimiento;
       this.localidad = localidad;
       this.calle = calle;
       this.numero = numero;
       this.puerta = puerta;
       this.piso = piso;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.citases = citases;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Enfermeros getEnfermeros() {
        return this.enfermeros;
    }
    
    public void setEnfermeros(Enfermeros enfermeros) {
        this.enfermeros = enfermeros;
    }
    public Medicos getMedicos() {
        return this.medicos;
    }
    
    public void setMedicos(Medicos medicos) {
        this.medicos = medicos;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public String getSip() {
        return this.sip;
    }
    
    public void setSip(String sip) {
        this.sip = sip;
    }
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido1() {
        return this.apellido1;
    }
    
    public void setApellido1(String apellido1) {
        this.apellido1 = apellido1;
    }
    public String getApellido2() {
        return this.apellido2;
    }
    
    public void setApellido2(String apellido2) {
        this.apellido2 = apellido2;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    public String getLocalidad() {
        return this.localidad;
    }
    
    public void setLocalidad(String localidad) {
        this.localidad = localidad;
    }
    public String getCalle() {
        return this.calle;
    }
    
    public void setCalle(String calle) {
        this.calle = calle;
    }
    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }
    public String getPuerta() {
        return this.puerta;
    }
    
    public void setPuerta(String puerta) {
        this.puerta = puerta;
    }
    public String getPiso() {
        return this.piso;
    }
    
    public void setPiso(String piso) {
        this.piso = piso;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
    public Set getCitases() {
        return this.citases;
    }
    
    public void setCitases(Set citases) {
        this.citases = citases;
    }


}


