package model;
// Generated 19-dic-2023 22:25:50 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TratamientoArchivos generated by hbm2java
 */
public class TratamientoArchivos  implements java.io.Serializable {


     private long id;
     private Tratamientos tratamientos;
     private String archivo;
     private Date createdAt;
     private Date updatedAt;

    public TratamientoArchivos() {
    }

	
    public TratamientoArchivos(long id, String archivo) {
        this.id = id;
        this.archivo = archivo;
    }
    public TratamientoArchivos(long id, Tratamientos tratamientos, String archivo, Date createdAt, Date updatedAt) {
       this.id = id;
       this.tratamientos = tratamientos;
       this.archivo = archivo;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public Tratamientos getTratamientos() {
        return this.tratamientos;
    }
    
    public void setTratamientos(Tratamientos tratamientos) {
        this.tratamientos = tratamientos;
    }
    public String getArchivo() {
        return this.archivo;
    }
    
    public void setArchivo(String archivo) {
        this.archivo = archivo;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }




}


